// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2024, 11:21:08 AM
const configMerger = require("/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/plugins/**/*.{js,ts,mjs}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/stores/**/*.{js,ts,mjs}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/composables/**/*.{js,ts,mjs}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/utils/**/*.{js,ts,mjs}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/imac/code_pro/try/tiy/cat-case/nuxt-cat-app/app.config.{js,ts,mjs}"] } }));

module.exports = config
